// Generated by map2h

#include <z80/types.h>

#define pfn_options_set_state ((void (*)(Option*,BYTE))0x4048)
#define pfn_options_set_type ((void (*)(Option*,BYTE))0x4070)
#define pfn_options_init ((void (*)())0x414F)
#define pfn_options_add_ex ((Option* (*)(const char*,BYTE,BYTE,WORD,WORD))0x4100)
#define pfn_options_get_state ((BYTE (*)(Option*))0x4016)
#define pfn_options_get_type ((BYTE (*)(Option*))0x4033)
#define pfn_options_add ((Option* (*)(const char*,BYTE,BYTE))0x4092)
